FROM docker.io/node:lts-alpine as build

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

FROM docker.io/nginx:1-alpine
COPY --from=build /app/dist /usr/share/nginx/html

